global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'

  - job_name: 'worker-image'
    static_configs:
      - targets: ['worker-image:9090']
    metrics_path: '/metrics'

  - job_name: 'worker-video'
    static_configs:
      - targets: ['worker-video:9090']
    metrics_path: '/metrics'
