apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workers
  labels:
    app: workers
spec:
  namespaceSelector:
    matchNames:
      - file-processor
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - worker-image
          - worker-video
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
