---
k3s_role: server

k3s_server_args:
  - --disable traefik
  - --disable servicelb
  - --flannel-iface enp7s0
  - --node-ip {{ private_ip }}
  - --advertise-address {{ private_ip }}
  - --write-kubeconfig-mode 644
